<?xml version="1.0" encoding="UTF-8"?>
<!--
  lahu-latex.xsl
  XSLT 1.0 stylesheet: TEI Lex-0 (generated/tei/lahu.xml) to XeLaTeX source.

  Usage: see README-tei.md. Adapted from the Jaschke Tibetan-English
  Dictionary project's xslt/jaschke-latex.xsl (same workspace): same
  overall approach (a two-column layout, a handful of \newcommand
  entry-formatting macros, XSLT 1.0's substring-based latex-escape
  helper), simplified because Lahu is a single Latin-based script (no
  separate Tibetan font machinery needed) and extended for usg,
  multiple example/translation pairs, sense/@n numbering, and letter
  dividers.

  IMPORTANT: this stylesheet emits BODY CONTENT ONLY (the dictionary
  entries), not a compilable document by itself. The surrounding
  document (documentclass, packages, fonts, the entry-formatting
  macros this content calls, title page, table of contents, and the
  multicols wrapper this content is \input into) lives in
  src/latex/lahu-master.tex, a hand-authored scaffold. Compile that
  file with XeLaTeX, not the output of this stylesheet directly; see
  README-tei.md. This split exists so the title page / TOC / front-
  and-back matter can be edited by hand without touching generated
  output, and so this file's own output is just data, safe to
  regenerate at any time.

  Requires XeLaTeX (not pdfLaTeX) for Unicode support. Body font
  (DejaVu Serif, chosen for broad Unicode coverage of IPA Extensions
  and combining diacritical marks; Lahu's tone marks are combining
  accents over vowels and consonants, e.g. g with combining diaeresis
  for g̈, and because it ships with most complete TeX Live
  installations) is set via \setmainfont in lahu-master.tex, not here;
  see that file to change it, e.g. to "Charis SIL" or "Doulos SIL" if
  DejaVu Serif isn't available.
-->
<xsl:stylesheet
  version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:tei="http://www.tei-c.org/ns/1.0"
  xmlns:xml="http://www.w3.org/XML/1998/namespace"
  exclude-result-prefixes="tei">

  <xsl:output method="text" encoding="UTF-8"/>

  <!-- Parameters -->
  <!-- Set to 1 to include editorial notes from the pipeline; 0 to suppress -->
  <xsl:param name="show-editorial-notes">0</xsl:param>


  <!-- ══════════════════════════════════════════════════════════════════════
       ROOT: emit body content only; see src/latex/lahu-master.tex for
       the rest of the document. Not indented/wrapped in its own
       multicols: the master file opens multicols before \input-ing
       this file's output and closes it after.
       ══════════════════════════════════════════════════════════════════════ -->
  <xsl:template match="/">
    <xsl:text>%% Auto-generated by src/lahu-latex.xsl from generated/tei/lahu.xml.
%% Body content only -- the dictionary entries themselves. This is
%% \input from inside src/latex/lahu-master.tex's multicols block, so
%% it must not open its own \documentclass / \begin{document} /
%% \begin{multicols}; see that file and README-tei.md for the rest of
%% the document (preamble, entry-formatting macros, title page, TOC).
</xsl:text>

    <xsl:apply-templates select="//tei:div[@type='dictionary']/tei:entry"/>

    <xsl:text>
</xsl:text>
  </xsl:template>


  <!-- ══════════════════════════════════════════════════════════════════════
       ENTRY
       ══════════════════════════════════════════════════════════════════════ -->
  <xsl:template match="tei:entry">
    <xsl:text>
</xsl:text>
    <xsl:text>\headword{</xsl:text>
    <xsl:call-template name="latex-escape">
      <xsl:with-param name="text" select="tei:form/tei:orth"/>
    </xsl:call-template>
    <xsl:text>}</xsl:text>

    <xsl:if test="tei:gramGrp/tei:gram">
      <xsl:text>\graminfo{</xsl:text>
      <xsl:call-template name="latex-escape">
        <xsl:with-param name="text" select="tei:gramGrp/tei:gram"/>
      </xsl:call-template>
      <xsl:text>}</xsl:text>
    </xsl:if>

    <xsl:apply-templates select="tei:usg"/>
    <xsl:apply-templates select="tei:sense"/>
    <xsl:apply-templates select="tei:note[not(@type='editorial')]"/>
    <xsl:if test="$show-editorial-notes='1'">
      <xsl:apply-templates select="tei:note[@type='editorial']"/>
    </xsl:if>
    <xsl:apply-templates select="tei:cit[@type='example']"/>
    <xsl:apply-templates select="tei:re"/>
    <xsl:apply-templates select="tei:milestone"/>
  </xsl:template>


  <!-- ══════════════════════════════════════════════════════════════════════
       USAGE LABEL
       ══════════════════════════════════════════════════════════════════════ -->
  <xsl:template match="tei:usg[@type='etym']">
    <xsl:text>\usgetym{</xsl:text>
    <xsl:call-template name="latex-escape">
      <xsl:with-param name="text" select="."/>
    </xsl:call-template>
    <xsl:text>}</xsl:text>
  </xsl:template>

  <xsl:template match="tei:usg[@type='label']">
    <xsl:text>\usglabel{</xsl:text>
    <xsl:call-template name="latex-escape">
      <xsl:with-param name="text" select="."/>
    </xsl:call-template>
    <xsl:text>}</xsl:text>
  </xsl:template>


  <!-- ══════════════════════════════════════════════════════════════════════
       SENSE
       ══════════════════════════════════════════════════════════════════════ -->
  <xsl:template match="tei:sense">
    <xsl:if test="@n">
      <xsl:text>\sensenum{</xsl:text>
      <xsl:value-of select="@n"/>
      <xsl:text>}</xsl:text>
    </xsl:if>
    <xsl:call-template name="latex-escape">
      <xsl:with-param name="text" select="tei:def"/>
    </xsl:call-template>
    <xsl:text> </xsl:text>
  </xsl:template>


  <!-- ══════════════════════════════════════════════════════════════════════
       NOTE (top-level \notetext, or \subnotetext inside a sub-entry)
       ══════════════════════════════════════════════════════════════════════ -->
  <xsl:template match="tei:note[not(@type='editorial')]">
    <xsl:choose>
      <xsl:when test="parent::tei:re">
        <xsl:text>\subnotetext{</xsl:text>
      </xsl:when>
      <xsl:otherwise>
        <xsl:text>\notetext{</xsl:text>
      </xsl:otherwise>
    </xsl:choose>
    <xsl:call-template name="latex-escape">
      <xsl:with-param name="text" select="."/>
    </xsl:call-template>
    <xsl:text>}</xsl:text>
  </xsl:template>

  <xsl:template match="tei:note[@type='editorial']">
    <xsl:text>\editorialnote{</xsl:text>
    <xsl:call-template name="latex-escape">
      <xsl:with-param name="text" select="."/>
    </xsl:call-template>
    <xsl:text>}</xsl:text>
  </xsl:template>


  <!-- ══════════════════════════════════════════════════════════════════════
       EXAMPLE + TRANSLATION (top-level \examplecit, or \subexamplecit
       inside a sub-entry)
       ══════════════════════════════════════════════════════════════════════ -->
  <xsl:template match="tei:cit[@type='example']">
    <xsl:choose>
      <xsl:when test="parent::tei:re">
        <xsl:text>\subexamplecit{</xsl:text>
      </xsl:when>
      <xsl:otherwise>
        <xsl:text>\examplecit{</xsl:text>
      </xsl:otherwise>
    </xsl:choose>
    <xsl:call-template name="latex-escape">
      <xsl:with-param name="text" select="tei:quote"/>
    </xsl:call-template>
    <xsl:text>}{</xsl:text>
    <xsl:if test="tei:cit[@type='translation']">
      <xsl:call-template name="latex-escape">
        <xsl:with-param name="text" select="tei:cit[@type='translation']/tei:quote"/>
      </xsl:call-template>
    </xsl:if>
    <xsl:text>}</xsl:text>
  </xsl:template>


  <!-- ══════════════════════════════════════════════════════════════════════
       RELATED ENTRY (sub-entry / compound form)

       \subentry{}{} carries only the headword-line content (gram/usg/
       sense), exactly mirroring how \headword's paragraph carries the
       top-level entry's headword line; note and example are applied
       afterward as their own paragraphs (via the context-aware
       templates above), exactly mirroring the top-level entry template.
       ══════════════════════════════════════════════════════════════════════ -->
  <xsl:template match="tei:re">
    <xsl:variable name="hw" select="tei:form/tei:orth"/>
    <xsl:text>
\subentry{</xsl:text>
    <xsl:call-template name="latex-escape">
      <xsl:with-param name="text" select="$hw"/>
    </xsl:call-template>
    <xsl:text>}{</xsl:text>
    <xsl:if test="tei:gramGrp/tei:gram">
      <xsl:text>\graminfo{</xsl:text>
      <xsl:call-template name="latex-escape">
        <xsl:with-param name="text" select="tei:gramGrp/tei:gram"/>
      </xsl:call-template>
      <xsl:text>}</xsl:text>
    </xsl:if>
    <xsl:apply-templates select="tei:usg"/>
    <xsl:apply-templates select="tei:sense"/>
    <xsl:text>}</xsl:text>
    <xsl:apply-templates select="tei:note[not(@type='editorial')]"/>
    <xsl:if test="$show-editorial-notes='1'">
      <xsl:apply-templates select="tei:note[@type='editorial']"/>
    </xsl:if>
    <xsl:apply-templates select="tei:cit[@type='example']"/>
    <xsl:apply-templates select="tei:milestone"/>
  </xsl:template>


  <!-- ══════════════════════════════════════════════════════════════════════
       LETTER DIVIDER
       ══════════════════════════════════════════════════════════════════════ -->
  <xsl:template match="tei:milestone[@unit='letter']">
    <xsl:text>
\dividerletter{</xsl:text>
    <xsl:call-template name="latex-escape">
      <xsl:with-param name="text" select="@n"/>
    </xsl:call-template>
    <xsl:text>}
</xsl:text>
  </xsl:template>

  <!-- Suppress teiHeader -->
  <xsl:template match="tei:teiHeader"/>


  <!-- ══════════════════════════════════════════════════════════════════════
       UTILITY: LaTeX character escaping (same recursive substring-based
       approach as jaschke-latex.xsl's latex-escape/str-replace, since
       XSLT 1.0 has no built-in string-replace function)
       ══════════════════════════════════════════════════════════════════════ -->
  <xsl:template name="latex-escape">
    <xsl:param name="text"/>
    <xsl:variable name="step1">
      <xsl:call-template name="str-replace">
        <xsl:with-param name="text" select="$text"/>
        <xsl:with-param name="from">\</xsl:with-param>
        <xsl:with-param name="to">\textbackslash{}</xsl:with-param>
      </xsl:call-template>
    </xsl:variable>
    <xsl:variable name="step2">
      <xsl:call-template name="str-replace">
        <xsl:with-param name="text" select="$step1"/>
        <xsl:with-param name="from">&amp;</xsl:with-param>
        <xsl:with-param name="to">\&amp;</xsl:with-param>
      </xsl:call-template>
    </xsl:variable>
    <xsl:variable name="step3">
      <xsl:call-template name="str-replace">
        <xsl:with-param name="text" select="$step2"/>
        <xsl:with-param name="from">%</xsl:with-param>
        <xsl:with-param name="to">\%</xsl:with-param>
      </xsl:call-template>
    </xsl:variable>
    <xsl:variable name="step4">
      <xsl:call-template name="str-replace">
        <xsl:with-param name="text" select="$step3"/>
        <xsl:with-param name="from">$</xsl:with-param>
        <xsl:with-param name="to">\$</xsl:with-param>
      </xsl:call-template>
    </xsl:variable>
    <xsl:variable name="step5">
      <xsl:call-template name="str-replace">
        <xsl:with-param name="text" select="$step4"/>
        <xsl:with-param name="from">#</xsl:with-param>
        <xsl:with-param name="to">\#</xsl:with-param>
      </xsl:call-template>
    </xsl:variable>
    <xsl:variable name="step6">
      <xsl:call-template name="str-replace">
        <xsl:with-param name="text" select="$step5"/>
        <xsl:with-param name="from">_</xsl:with-param>
        <xsl:with-param name="to">\_</xsl:with-param>
      </xsl:call-template>
    </xsl:variable>
    <xsl:variable name="step7">
      <xsl:call-template name="str-replace">
        <xsl:with-param name="text" select="$step6"/>
        <xsl:with-param name="from">{</xsl:with-param>
        <xsl:with-param name="to">\{</xsl:with-param>
      </xsl:call-template>
    </xsl:variable>
    <xsl:variable name="step8">
      <xsl:call-template name="str-replace">
        <xsl:with-param name="text" select="$step7"/>
        <xsl:with-param name="from">}</xsl:with-param>
        <xsl:with-param name="to">\}</xsl:with-param>
      </xsl:call-template>
    </xsl:variable>
    <!-- '^' and '~' are TeX active characters outside math mode ('^'
         especially: a bare caret triggers "Missing $ inserted" and
         aborts the compile). Both occur literally in a few dozen
         comparative-linguistics notes (e.g. "ga^" for a syllable later
         meant to carry a circumflex, or "~" marking free variation), so
         these must be escaped too, not just the classic LaTeX special
         seven. Introduced as their own step, after the backslash step,
         so the backslash inside \textasciicircum{}/\textasciitilde{}
         doesn't get re-escaped. -->
    <xsl:variable name="step9">
      <xsl:call-template name="str-replace">
        <xsl:with-param name="text" select="$step8"/>
        <xsl:with-param name="from">^</xsl:with-param>
        <xsl:with-param name="to">\textasciicircum{}</xsl:with-param>
      </xsl:call-template>
    </xsl:variable>
    <xsl:variable name="step10">
      <xsl:call-template name="str-replace">
        <xsl:with-param name="text" select="$step9"/>
        <xsl:with-param name="from">~</xsl:with-param>
        <xsl:with-param name="to">\textasciitilde{}</xsl:with-param>
      </xsl:call-template>
    </xsl:variable>
    <!-- Straight quotes/apostrophes must render as straight glyphs, not
         curly ones: there are no curly quotes anywhere in the source
         (see README.md), only plain ' and ", always used on both sides
         of a quotation. \textquotesingle{}/\textquotedbl{} guarantee the
         straight glyph regardless of any font ligature feature (this
         used to be handled by turning off fontspec's Ligatures=TeX in
         lahu-master.tex alone, but that's a font-level setting; escaping
         here too means this stays correct even if that setting is ever
         changed back). Steps 11-12, after the backslash step, so the
         backslashes inside these commands' own braces don't get
         re-escaped, same reasoning as steps 9-10 above. -->
    <xsl:variable name="step11">
      <xsl:call-template name="str-replace">
        <xsl:with-param name="text" select="$step10"/>
        <xsl:with-param name="from">'</xsl:with-param>
        <xsl:with-param name="to">\textquotesingle{}</xsl:with-param>
      </xsl:call-template>
    </xsl:variable>
    <xsl:variable name="step12">
      <xsl:call-template name="str-replace">
        <xsl:with-param name="text" select="$step11"/>
        <xsl:with-param name="from">"</xsl:with-param>
        <xsl:with-param name="to">\textquotedbl{}</xsl:with-param>
      </xsl:call-template>
    </xsl:variable>
    <xsl:value-of select="$step12"/>
  </xsl:template>

  <!-- Recursive string replace (XSLT 1.0) -->
  <xsl:template name="str-replace">
    <xsl:param name="text"/>
    <xsl:param name="from"/>
    <xsl:param name="to"/>
    <xsl:choose>
      <xsl:when test="contains($text, $from)">
        <xsl:value-of select="substring-before($text, $from)"/>
        <xsl:value-of select="$to"/>
        <xsl:call-template name="str-replace">
          <xsl:with-param name="text" select="substring-after($text, $from)"/>
          <xsl:with-param name="from" select="$from"/>
          <xsl:with-param name="to" select="$to"/>
        </xsl:call-template>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$text"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

</xsl:stylesheet>
